import type { SeoToolGroup } from "./seoToolsLinks"

/** قائمة dalisoft/awesome-ui-libraries (MIT): روابط فقط، مرتبة حسب أقسام القائمة الأصلية. */
export const UI_LIBRARY_GROUPS: SeoToolGroup[] = [
  {
    title: "Other my awesome lists",
    links: [
      { label: "awesome-hosting", href: "https://github.com/dalisoft/awesome-hosting" },
      { label: "awesome-storage", href: "https://github.com/dalisoft/awesome-storage" },
      { label: "awesome-ai-coding", href: "https://github.com/dalisoft/awesome-ai-coding" },
      { label: "awesome-cms", href: "https://github.com/dalisoft/awesome-cms" },
    ],
  },
  {
    title: "Inspiration websites",
    links: [
      { label: "Awwwards", href: "https://www.awwwards.com/websites" },
      { label: "Best Design on X", href: "https://bestdesignsonx.com" },
      { label: "Best Website", href: "https://bestwebsite.gallery" },
      { label: "Codrops", href: "https://tympanus.net/codrops/webzibition" },
      { label: "CSS Design Awards", href: "https://www.cssdesignawards.com" },
      { label: "Dark Mode Design", href: "https://www.darkmodedesign.com" },
      { label: "Godly", href: "https://godly.website" },
      { label: "GSAP Showcase", href: "https://gsap.com/showcase" },
      { label: "Httpster", href: "https://httpster.net" },
      { label: "Landbook", href: "https://land-book.com" },
      { label: "Lapa Ninja", href: "https://www.lapa.ninja" },
      { label: "MaxiBestOf", href: "https://maxibestof.one" },
      { label: "Minimal", href: "https://minimal.gallery" },
      { label: "Mobbin", href: "https://mobbin.com" },
      { label: "One Page Love", href: "https://onepagelove.com" },
      { label: "Page Flows", href: "https://pageflows.com" },
      { label: "Site of Sites", href: "https://www.siteofsites.co" },
      { label: "SiteInspire", href: "https://www.siteinspire.com" },
      { label: "The FWA", href: "https://thefwa.com" },
      { label: "Visual Journal", href: "https://visualjournal.it" },
      { label: "visuelle.", href: "https://visuelle.co.uk" },
    ],
  },
  {
    title: "Components",
    links: [
      { label: "AI Canvas (PRO)", href: "https://aicanvas.me" },
      { label: "AI Elements", href: "https://ai-sdk.dev/elements" },
      { label: "assistant-ui", href: "https://www.assistant-ui.com" },
      { label: "Badtzui (PRO)", href: "https://www.badtz-ui.com" },
      { label: "bazza UI", href: "https://ui.bazza.dev" },
      { label: "BlitzCharts", href: "https://blitz-charts.vercel.app" },
      { label: "blocks", href: "https://blocks.so" },
      { label: "Chanhdai", href: "https://chanhdai.com/components" },
      { label: "Codrops", href: "https://tympanus.net/codrops/demos" },
      { label: "CopilotKit", href: "https://www.copilotkit.ai" },
      { label: "cult ui", href: "https://www.cult-ui.com" },
      { label: "Dice", href: "https://www.diceui.com" },
      { label: "Eldoraui", href: "https://www.eldoraui.site" },
      { label: "Elements", href: "https://www.tryelements.dev" },
      { label: "ElevenLabs", href: "https://ui.elevenlabs.io" },
      { label: "evilcharts", href: "https://evilcharts.com" },
      { label: "fancy", href: "https://www.fancycomponents.dev" },
      { label: "Formedible", href: "https://formedible.dev" },
      { label: "Indev/Ui (PRO)", href: "https://ui.lndev.me" },
      { label: "Kibo UI", href: "https://www.kibo-ui.com" },
      { label: "Kitze UI", href: "https://ui.kitze.io" },
      { label: "kokonut UI (PRO)", href: "https://kokonutui.com" },
      { label: "Luxe", href: "https://www.luxeui.com" },
      { label: "Markstream", href: "https://markstream.simonhe.me" },
      { label: "Motion Core", href: "https://motion-core.dev" },
      { label: "Motion Primitives (PRO)", href: "https://motion-primitives.com" },
      { label: "Osmium", href: "https://osmium.intface.io" },
      { label: "PaceUI", href: "https://ui.paceui.com" },
      { label: "PatternCraft", href: "https://patterncraft.fun" },
      { label: "prompt-kit", href: "https://www.prompt-kit.com" },
      { label: "Puck", href: "https://puckeditor.com" },
      { label: "Raulcarini UI", href: "https://ui.raulcarini.dev" },
      { label: "React Bits", href: "https://reactbits.dev" },
      { label: "Reactiive Demos", href: "https://reactiive.io/demos" },
      { label: "Riffle", href: "https://reactivepixels.github.io/riffle" },
      { label: "Serenity Ui", href: "https://www.serenity-ui.com" },
      { label: "SKIPER-UI (PRO)", href: "https://skiper-ui.com" },
      { label: "Smooth UI", href: "https://smoothui.dev" },
      { label: "SolaceUI", href: "https://www.solaceui.com" },
      { label: "Supabase UI", href: "https://supabase.com/ui" },
      { label: "Tailark (PRO)", href: "https://tailark.com" },
      { label: "UI SFX", href: "https://uisfx.com" },
      { label: "visual-effect", href: "https://effect.kitlangton.com" },
      { label: "XD UI", href: "https://ui.surajgaud.com" },
    ],
  },
  {
    title: "UI Tailwind CSS",
    links: [
      { label: "Float UI", href: "https://floatui.com" },
      { label: "Flowbite", href: "https://flowbite.com" },
      { label: "Tailgrids (PRO)", href: "https://tailgrids.com" },
      { label: "TW Elements (PRO)", href: "https://tw-elements.com" },
    ],
  },
  {
    title: "UI Shadcn",
    links: [
      { label: "8bitcn", href: "https://www.8bitcn.com" },
      { label: "9ui", href: "https://www.9ui.dev" },
      { label: "Aceternity (PRO)", href: "https://ui.aceternity.com" },
      { label: "Alignui (PRO)", href: "https://www.alignui.com" },
      { label: "Animate", href: "https://animate-ui.com" },
      { label: "Base", href: "https://basecn.dev" },
      { label: "dotUI", href: "https://dotui.org" },
      { label: "Hese", href: "https://github.com/preetsuthar17/HeseUI" },
      { label: "Hexta (PRO)", href: "https://hextaui.com" },
      { label: "JollyUI", href: "https://www.jollyui.dev" },
      { label: "Magic", href: "https://magicui.design" },
      { label: "Origin", href: "https://coss.com/origin" },
      { label: "preline (PRO)", href: "https://preline.co" },
      { label: "RetroUI (PRO)", href: "https://www.retroui.dev" },
      { label: "REUI", href: "https://reui.io" },
      { label: "shacdn/ui-blocks (PRO)", href: "https://www.shadcnblocks.com" },
      { label: "Shadcn Space (PRO)", href: "https://shadcnspace.com/" },
      { label: "shadcn Store (PRO)", href: "https://shadcnstore.com" },
      { label: "shadcn-admin-kit", href: "https://marmelab.com/shadcn-admin-kit" },
      { label: "shadcn/studio (PRO)", href: "https://shadcnstudio.com" },
      { label: "shadcn/ui", href: "https://ui.shadcn.com" },
      { label: "shadcn/ui Blocks (PRO)", href: "https://www.shadcnui-blocks.com" },
      { label: "shadcn/ui Kit (PRO)", href: "https://shadcnuikit.com" },
      { label: "Spectrum", href: "https://ui.spectrumhq.in" },
      { label: "tremor", href: "https://tremor.so" },
      { label: "Untitled (PRO)", href: "https://www.untitledui.com" },
      { label: "Shadcn Dashboard (PRO)", href: "https://shadcndashboard.dev/" },
    ],
  },
  {
    title: "UI Libraries",
    links: [
      { label: "Ant-Design", href: "https://ant.design" },
      { label: "Ariakit (PRO)", href: "https://ariakit.org" },
      { label: "ARK (PRO)", href: "https://ark-ui.com" },
      { label: "Base", href: "https://base-ui.com" },
      { label: "Baseweb", href: "https://baseweb.design" },
      { label: "Blueprint", href: "https://blueprintjs.com" },
      { label: "Bootstrap", href: "https://getbootstrap.com" },
      { label: "Bulma", href: "https://bulma.io" },
      { label: "Carbon", href: "https://carbondesignsystem.com" },
      { label: "chakra (PRO)", href: "https://chakra-ui.com" },
      { label: "Core (PRO)", href: "https://coreui.io/bootstrap/docs/getting-started" },
      { label: "daisyUI", href: "https://daisyui.com" },
      { label: "Evergreen", href: "https://github.com/segmentio/evergreen" },
      { label: "Fluent", href: "https://react.fluentui.dev" },
      { label: "FlyonUI", href: "https://flyonui.com" },
      { label: "Franken", href: "https://franken-ui.dev" },
      { label: "Geist", href: "https://geist-ui.dev" },
      { label: "gluestack-ui", href: "https://gluestack.io" },
      { label: "GPUI components", href: "https://huacnlee.github.io/gpui-component-story-web" },
      { label: "GPUIX", href: "https://github.com/remorses/gpuix" },
      { label: "grommet", href: "https://v2.grommet.io" },
      { label: "headlessUI", href: "https://headlessui.com" },
      { label: "Hero (PRO)", href: "https://www.heroui.com" },
      { label: "Hyper", href: "https://www.hyperui.dev" },
      { label: "Mantine", href: "https://mantine.dev" },
      { label: "Mdb-React-Ui-Kit (PRO)", href: "https://mdbootstrap.com" },
      { label: "MUI Material", href: "https://mui.com/material-ui" },
      { label: "PARK", href: "https://park-ui.com" },
      { label: "Paste", href: "https://paste.twilio.design" },
      { label: "PatternFly", href: "https://www.patternfly.org" },
      { label: "Primer", href: "https://primer.style" },
      { label: "PRIMEReact", href: "https://primereact.org" },
      { label: "Radix Primitives", href: "https://www.radix-ui.com/primitives" },
      { label: "Radix Themes", href: "https://www.radix-ui.com/themes" },
      { label: "React Aria", href: "https://react-spectrum.adobe.com/react-aria" },
      { label: "React Suite", href: "https://rsuitejs.com" },
      { label: "Ring", href: "https://jetbrains.github.io/ring-ui" },
      { label: "RizzUI", href: "https://www.rizzui.com" },
      { label: "Shards (PRO)", href: "https://designrevision.com/docs/shards-react" },
      { label: "Shoelace", href: "https://webawesome.com" },
      { label: "TAMA GUI (PRO)", href: "https://tamagui.dev/ui/intro" },
    ],
  },
  {
    title: "Collections / UI components",
    links: [
      { label: "21st Authors", href: "https://21st.dev/authors" },
      { label: "21st", href: "https://21st.dev" },
      { label: "Awesome Design Resources List", href: "https://github.com/darelova/Awesome-Design-Resources-List" },
      { label: "Awesome React Design Systems", href: "https://github.com/jbranchaud/awesome-react-design-systems" },
      { label: "Awesome UI component library", href: "https://github.com/anubhavsrivastava/awesome-ui-component-library" },
      { label: "awesome-css-frameworks", href: "https://github.com/troxler/awesome-css-frameworks" },
      { label: "awesome-design-systems", href: "https://github.com/alexpate/awesome-design-systems" },
      { label: "awesome-minimalist", href: "https://github.com/neiesc/awesome-minimalist" },
      { label: "awesome-react-components", href: "https://github.com/brillout/awesome-react-components" },
      { label: "awesome-shadcn/ui", href: "https://github.com/birobirobiro/awesome-shadcn-ui" },
      { label: "Design Resources for Developers", href: "https://github.com/bradtraversy/design-resources-for-developers" },
      { label: "TOOOLS.design", href: "https://www.toools.design" },
      { label: "UIVerse", href: "https://uiverse.io" },
    ],
  },
  {
    title: "Templates / Dashboards",
    links: [
      { label: "Aniq-ui Marketplace", href: "https://www.aniq-ui.com" },
      { label: "Dashboard & Landing", href: "https://github.com/shadcnstore/shadcn-dashboard-landing-template" },
      { label: "Horizon (PRO)", href: "https://horizon-ui.com" },
      { label: "K8S UI", href: "https://github.com/PRO-Robotech/openapi-ui" },
      { label: "Next Shadcn Dashboard", href: "https://github.com/Kiranism/next-shadcn-dashboard-starter" },
      { label: "Shadboard", href: "https://shadboard.vercel.app/" },
      { label: "Shadcn Admin", href: "https://shadcn-admin.netlify.app" },
      { label: "shadcn-vite-starter", href: "https://starter.7ovr.com" },
      { label: "Square UI Pro (PRO)", href: "https://pro.lndev.me" },
      { label: "Tabler", href: "https://tabler.io/admin-template" },
      { label: "TailAdmin (PRO)", href: "https://tailadmin.com" },
      { label: "Tailwindadmin (PRO)", href: "https://tailwind-admin.com/" },
    ],
  },
  {
    title: "Templates / Other",
    links: [
      { label: "Fonttrio", href: "https://www.fonttrio.xyz" },
      { label: "Homeguardian", href: "https://homeguardian-shadcn-landing-page.vercel.app" },
      { label: "Origin Layouts", href: "https://originui.com/layouts" },
      { label: "Page UI", href: "https://github.com/danmindru/page-ui" },
      { label: "Shadify", href: "https://github.com/tylerslaton/shadify" },
    ],
  },
  {
    title: "Styling",
    links: [
      { label: "Tweakcn (PRO)", href: "https://tweakcn.com" },
    ],
  },
  {
    title: "UI Designs",
    links: [
      { label: "Shadcn Design (PRO)", href: "https://www.shadcndesign.com" },
      { label: "shadcraft (PRO)", href: "https://shadcraft.com" },
    ],
  },
  {
    title: "UI Designs / AI",
    links: [
      { label: "DesignRocket (PRO)", href: "https://designrocket.io" },
      { label: "Motion Sites", href: "https://motionsites.ai" },
      { label: "_Frontend Design_", href: "https://github.com/anthropics/skills" },
      { label: "_Landing_", href: "https://github.com/alirezarezvani/claude-skills" },
      { label: "`DESIGN.md`", href: "https://stitch.withgoogle.com/docs/design-md/specification" },
      { label: "anydesign", href: "https://github.com/uxKero/anydesign" },
      { label: "awesome-design-skills", href: "https://www.typeui.sh/design-skills" },
      { label: "Hallmark", href: "https://www.usehallmark.com" },
      { label: "Lazyweb", href: "https://github.com/aboul3ata/lazyweb-skill" },
      { label: "mbs-skills", href: "https://github.com/madebyshun/mbs-skills" },
      { label: "Mobbin UI", href: "https://github.com/ddruids/mobbin-skill" },
      { label: "parhamb-design-skills", href: "https://github.com/parhamb/design-skills" },
      { label: "Tambo AI", href: "https://tambo.co" },
      { label: "Taste Skill", href: "https://www.tasteskill.dev" },
      { label: "UI UX Pro Max", href: "https://www.uupm.cc" },
      { label: "AIDesigner (PRO)", href: "https://www.aidesigner.ai/docs/mcp" },
      { label: "OpenDesign", href: "https://open-design.ai" },
    ],
  },
]
